CREATE DATABASE DB_BiblioTech;

USE DB_BiblioTech;

CREATE TABLE USUARIO (
  USE_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USE_NICK VARCHAR(30) NOT NULL UNIQUE,  /* USAR NO LOGIN */
  USE_SENHA VARCHAR(100) NOT NULL,   /* USAR NO LOGIN */
  USE_TYPE ENUM('ADMIN', 'BIBLIOTECARIO', 'CLIENTE') NOT NULL,   /* USAR NO LOGIN */
  USE_NOME VARCHAR(50) NOT NULL,
  USE_SOBRENOME VARCHAR(50),
  USE_DATANASC DATE,
  USE_EMAIL VARCHAR(100) NOT NULL UNIQUE,
  USE_CRIA DATETIME,
  USE_SEXO ENUM ('MASC', 'FEM', 'OUTRO'),
  USE_CPF VARCHAR (11)
);

INSERT INTO USUARIO VALUES
  ( NULL, 'admin', 'admin', 'ADMIN', 'Bruno', 'Fernades', '1990-02-28', 'bruno@email.com',  NOW(), 'MASC', '11111111111'),
  ( NULL, 'sergio', 'sergio', 'BIBLIOTECARIO', 'Sérgio', 'Beltrão', '1990-02-28', 'sergio@email.com',  NOW(), 'MASC', '22222222222'),
  ( NULL, 'john', 'john', 'CLIENTE', 'Jonatas', 'Sousa', '1990-02-28', 'john@email.com',  NOW(), 'MASC','33333333333');
  
CREATE TABLE ENDERECO (
  END_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  END_RUA VARCHAR(150),
  END_NUM INT,
  END_COMP VARCHAR(50),
  END_BAIRRO VARCHAR(100),
  END_CIDADE VARCHAR(100),
  END_UF VARCHAR (2),
  END_PAIS VARCHAR(50),
  END_CEP VARCHAR(10)
);

INSERT INTO ENDERECO VALUES (NULL, 'Dolores', 13, 'APTO', 'Mooca', 'Sao Paulo', 'SP', 'BRASIL', '987321654');
    
 CREATE TABLE TELEFONE (
	TEL_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	TEL_TIPO ENUM ('RESIDENCIAL', 'COMERCIAL', 'CELULAR')NOT NULL,
	TEL_TELEFONE VARCHAR (15) NOT NULL	
);

INSERT INTO TELEFONE VALUES (NULL, 'CELULAR', '11 994545058'), 
 (NULL, 'CELULAR', '11 975630714'), (NULL, 'CELULAR', '11 91340-9833');
 
CREATE TABLE FUNCIONARIO (
  FUN_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  FUN_ENTRADA DATE NOT NULL,
  FUN_SAIDA DATE,
  FUN_SALARIO DECIMAL(10, 2) NOT NULL
);
  
CREATE TABLE LIVRO ( 
	ID_LIVRO INT PRIMARY KEY AUTO_INCREMENT,
	LIV_NOME_LIVRO VARCHAR (100) NOT NULL,
	LIV_ISBN VARCHAR (100)NOT NULL,
	LIV_ANO INT, 
	LIV_PAGINA INT NOT NULL,
	LIV_QUANTIDADE INT,
	LIV_CATEGORIA VARCHAR (50)NOT NULL,
	LIV_PRECO DECIMAL (6,2),
    LIV_SUBCATEGORIA VARCHAR (50),
    LIV_IDIOMA VARCHAR (10)
);

INSERT INTO LIVRO VALUES(
	NULL, 'O Segredo das Estrelas', '978-1234567890', 1980, 320, 10,  'Ficção Científica', '180.20', '40 - Programação', 'Portugues');
    
CREATE TABLE AUTOR(
	ID_AUTOR INT PRIMARY KEY AUTO_INCREMENT,
	AUT_NOME_AUTOR VARCHAR (100)NOT NULL,
	AUT_DATA_NASC DATE,
	AUT_NACIONALIDADE VARCHAR (50) ,
	AUT_BIBLIOGRAFIA TEXT,
	AUT_SEXO ENUM ('MASC', 'FEM', 'OUTRO')
);
	
INSERT INTO AUTOR ( AUT_NOME_AUTOR, AUT_DATA_NASC, AUT_NACIONALIDADE, AUT_SEXO) 
 VALUES ('Laura Bens', '1997-01-27', 'Brazil', 'FEM' );

CREATE TABLE EDITORA (
	ID_EDITORA  INT PRIMARY KEY AUTO_INCREMENT,
	EDT_NOME_EDITORA  VARCHAR (50) NOT NULL
	);
	
INSERT INTO EDITORA (EDT_NOME_EDITORA) VALUES ('Galáxia Editora');

CREATE TABLE FINANCEIRO ( 
	ID_FINANCEIRO INT NOT NULL PRIMARY KEY,
    FIN_SALDO DECIMAL (8,2) NOT NULL, /*criar codigo para ver salto total*/
    FIN_DATA_TRANSACAO DATE NOT NULL,
    FIN_TIPO ENUM ('PAGAMENTO', 'RECEBIDO'), /* usuar a resposta deste campo para soma ou subtrair do saldo */
    FIN_USUARIO INT NOT NULL, FOREIGN KEY (FIN_USUARIO) REFERENCES USUARIO(USE_ID)
);

CREATE TABLE AVALIACAO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    AVA_FK_LIVRO INT NOT NULL, FOREIGN KEY (AVA_FK_LIVRO) REFERENCES LIVRO (ID_LIVRO),
    AVA_USUARIO INT,
    AVA_TOTAL DECIMAL(6, 2), /* criar codigo para somar as notas dos usuarios */
    AVA_COMENTARIO TEXT,
    AVA_DATA_AVALIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    AVA_FK_USUARIO INT, FOREIGN KEY (AVA_FK_USUARIO) REFERENCES USUARIO (USE_ID)
);

/* APARTIR DESTA LINHA ESTAO AS TABELAS COM AS CHAVES ESTRANGEIRAS*/

/*TABELA DE CHAVES ESTRANGEIRAS DE LIVRO */
CREATE TABLE LIVRO_CHAVE (
	LIVRO_USER INT NOT NULL,
    LIVRO_AUTOR INT NOT NULL,
    LIVRO_EDITORA INT NOT NULL,
    PRIMARY KEY LIVRO_CHAVE (LIVRO_USER, LIVRO_AUTOR, LIVRO_EDITORA)
);

ALTER TABLE LIVRO_CHAVE ADD CONSTRAINT FOREIGN KEY (LIVRO_USER) REFERENCES USUARIO (USE_ID);
ALTER TABLE LIVRO_CHAVE ADD CONSTRAINT FOREIGN KEY (LIVRO_AUTOR) REFERENCES AUTOR (ID_AUTOR);
ALTER TABLE LIVRO_CHAVE ADD CONSTRAINT FOREIGN KEY (LIVRO_EDITORA) REFERENCES EDITORA (ID_EDITORA);

/*TABELA DE CHAVES ESTRANGEIRAS DE DADOS EDITORA */
CREATE TABLE EDITORA_CHAVE ( 
	EDITORA_AUTOR INT NOT NULL,
    EDITORA_TELEFONE INT NOT NULL,
    EDITORA_ENDERECO INT NOT NULL,
    PRIMARY KEY EDITORA_CHAVE (EDITORA_AUTOR, EDITORA_TELEFONE, EDITORA_ENDERECO)
);

ALTER TABLE EDITORA_CHAVE ADD CONSTRAINT FOREIGN KEY (EDITORA_AUTOR) REFERENCES AUTOR (ID_AUTOR);
ALTER TABLE EDITORA_CHAVE ADD CONSTRAINT FOREIGN KEY (EDITORA_TELEFONE) REFERENCES TELEFONE (TEL_ID);
ALTER TABLE EDITORA_CHAVE ADD CONSTRAINT FOREIGN KEY (EDITORA_ENDERECO) REFERENCES ENDERECO (END_ID);

/*TABELA DE CHAVES ESTRANGEIRAS TELEFONE */
CREATE TABLE TELEFONE_CHAVE ( 
	TELEFONE_AUTOR INT NOT NULL,
    TELEFONE_USER INT NOT NULL,
    PRIMARY KEY TELEFONE_CHAVE (TELEFONE_AUTOR, TELEFONE_USER)
);

ALTER TABLE TELEFONE_CHAVE ADD CONSTRAINT FOREIGN KEY (TELEFONE_AUTOR) REFERENCES AUTOR (ID_AUTOR);
ALTER TABLE TELEFONE_CHAVE ADD CONSTRAINT FOREIGN KEY (TELEFONE_USER) REFERENCES USUARIO (USE_ID);

/*TABELA DE CHAVES ESTRANGEIRAS TELEFONE */
CREATE TABLE ENDERECO_CHAVE ( 
	ENDERECO_AUTOR INT NOT NULL,
    ENDERECO_USER INT NOT NULL,
    PRIMARY KEY TELEFONE_CHAVE (ENDERECO_USER, ENDERECO_AUTOR)
);

ALTER TABLE ENDERECO_CHAVE ADD CONSTRAINT FOREIGN KEY (ENDERECO_AUTOR) REFERENCES AUTOR (ID_AUTOR);
ALTER TABLE ENDERECO_CHAVE ADD CONSTRAINT FOREIGN KEY (ENDERECO_USER) REFERENCES USUARIO (USE_ID);

/* SHOW COLUMNS FROM ENDERECO;
-- Na tabela USUARIO, a coluna USE_SENHA é uma senha e deve ser armazenada de forma segura, o uso de uma senha de texto simples não é recomendado.

INSERT INTO AVALIACAO (AVA_FK_LIVRO, AVA_USUARIO, AVA_TOTAL, AVA_COMENTARIO, AVA_FK_USUARIO)
VALUES (
  (SELECT ID_LIVRO FROM LIVRO WHERE LIV_NOME_LIVRO = 'O Segredo das Estrelas'),
    
  SELECT L.LIV_NOME_LIVRO, L.LIV_PAGINA, L.LIV_ANO, L.LIV_EDITORA, "
                + "A.AVA_COMENTARIO FROM LIVRO L LEFT JOIN AVALIACAO A "
                + "ON L.ID_LIVRO = A.AVA_FK_LIVRO LEFT JOIN CATEGORIA C ON "
                + "L.LIV_CATEGORIA = C.CAT_ID WHERE LIV_NOME_LIVRO = ?
      findTable();
    public void findTable(){
        TelaAvaliacaoDAO taDAO = new TelaAvaliacaoDAO(){
            taDAo.setDefaultCloseOperation(JFram.EXIT_ON_CLOSE);
            taDAO.setLayout(new FlowLayout());
                }
        
      /*  for (Avaliacao tv: taDAO.find());*
        
        
    }              
                
                
                
);




*/